sonar.projectKey=yohi_chronos-gate
sonar.organization=yohi
sonar.projectName=chronos-gate
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=tests/**

sonar.sourceEncoding=UTF-8
