#!/usr/bin/env bash
# Auto-generated by bootstrap.sh
GATEWAY_GIT_REF="${CHRONOS_GATEWAY_GIT_REF:-master}"
uvx --quiet --from "chronos-gate @ git+https://github.com/yohi/chronos-gate.git@${GATEWAY_GIT_REF}" \
  chronos-gate evaluate \
  --json-io \
  --policy-path "${CHRONOS_EVALUATOR_POLICY_PATH:-$HOME/.config/chronos/intents.yaml}"
