#!/usr/bin/env bash
# Auto-generated by bootstrap.sh
uvx --quiet --from "chronos-gate @ git+https://github.com/yohi/chronos-gate.git@5b11fd81ec1dc76897dbd74dec648005b85462ca" \
  chronos-gate evaluate \
  --json-io \
  --policy-path "${CHRONOS_EVALUATOR_POLICY_PATH:-$HOME/.config/chronos/intents.yaml}"
