#!/usr/bin/env bash
# Auto-generated by bootstrap.sh
GATEWAY_GIT_REF="${CHRONOS_GATEWAY_GIT_REF:-master}"

# Validate git ref format (alphanumeric, dots, hyphens, underscores, slashes)
if [[ ! "$GATEWAY_GIT_REF" =~ ^[a-zA-Z0-9._/-]+$ ]]; then
  echo "ERROR: Invalid CHRONOS_GATEWAY_GIT_REF format" >&2
  exit 1
fi

uvx --quiet --from "chronos-gate @ git+https://github.com/yohi/chronos-gate.git@${GATEWAY_GIT_REF}" \
  chronos-gate evaluate \
  --json-io \
  --policy-path "${CHRONOS_EVALUATOR_POLICY_PATH:-$HOME/.config/chronos/intents.yaml}"
